backend:
  name: git-gateway
  repo: SEALAB-Software/website
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blogg"
    folder: "src/pages/blogg"
    create: true
    description: "Blogg artikler. Her kan man lage, endre eller slette artikler."
    filter: {field: "templateKey", value: "blog-post"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Tittel", name: "title", widget: "string", hint: "Tittel på fanen og SEO tittel"}
      - {label: "Overskrift", name: "heading", widget: "string", hint: "Dette er overskriften man først ser under artikkel-bilde"}
      - {label: "Publiseringsdato", name: "date", widget: "datetime"}
      - {label: "Kort beskrivelse", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", hint: "Denne kan brukes til å velge hvilke aritkler som skal vises på Blogg-siden."}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false,}
      - {label: "Innhold", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", required: false, widget: "list", hint: "Denne kan brukes til å la brukeren finne relaterte artikler. OBS! Denne kan stå tom."}  
  - name: "apps"
    label: "Apper"
    folder: "src/pages/apper"
    create: true
    description: "Apper med tittel, bilde og beskrivende tekst. Her kan man lage, endre eller slette artikler. Alle disse sidene havner under sealab.no/apper/navnpåside.no"
    filter: {field: "templateKey", value: "software-page"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "software-page"}
      - {label: "Tittel", name: "title", widget: "string"}
      - {label: "Overskrift", name: "heading", widget: "string", hint: "H1 Overskrift"}
      - {label: "Underoverskrift", name: "subheading", widget: "text", hint: "Plasseres under overskrift"}
      - {label: "Featured Image", name: "featuredimage", widget: image}

      - label: "Todelt seksjon"
        name: "softwareDescription"
        widget: "object"
        fields:
          - {label: "Venstre overskrift", name: "heading", widget: "string"}
          - {label: "Venstre underoverskrift", name: "subheading", widget: "string"}
      - {label: "Høyre innhold", name: "body", widget: "markdown", }
      - {label: "SEO Beskrivelse", required: false, name: "seoDescription", widget: "text", hint: "Vises kun i søkemotorer og i meta-beskrivelser."}
      - {label: "Tags", name: "tags", required: false, widget: "list", hint: "Denne kan brukes til å la brukeren finne relaterte artikler. OBS! Denne kan stå tom."}
  - name: "software"
    label: "Sider som bruker Software mal"
    folder: "src/pages"
    create: true
    description: "Software sider som bruker Software mal. Her kan man lage, endre eller slette artikler. Disse sidene har ingen prefix, og havner derfor under sealab.no/navnpåside.no"
    filter: {field: "templateKey", value: "software-page"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "software-page"}
      - {label: "Tittel", name: "title", widget: "string"}
      - {label: "Overskrift", name: "title", widget: "string", hint: "H1 Overskrift"}
      - {label: "Underoverskrift", name: "subheading", widget: "text", hint: "Plasseres under overskrift"}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false,}

      - label: "Todelt seksjon"
        name: "softwareDescription"
        widget: "object"
        fields:
          - {label: "Venstre overskrift", name: "heading", widget: "string"}
          - {label: "Venstre underoverskrift", name: "subheading", widget: "string"}
      - {label: "Høyre innhold", name: "body", widget: "markdown", }
      - {label: "SEO Beskrivelse", name: "seoDescription", required: false, widget: "text", hint: "Vises kun i søkemotorer og i meta-beskrivelser."}
      - {label: "Tags", name: "tags", required: false, widget: "list", hint: "Denne kan brukes til å la brukeren finne relaterte artikler. OBS! Denne kan stå tom."}  
  - name: "pages"
    label: "Vanlige sider"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
